name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_linux:
    name: Test Linux
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run:  |
        sudo apt install coinor-libcbc-dev coinor-cbc
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --all-features
  
